name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          accept-android-sdk-licenses: 'true'
   
      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Prepare APK
        run: |
          mkdir -p apk-output
          APK=$(find app/build/outputs/apk -name "*.apk" | head -n 1)
          if [ -z "$APK" ]; then
            echo "APK bulunamadi!"
            exit 1
          fi
          cp "$APK" apk-output/NOVA-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NOVA-debug-APK
          path: apk-output/NOVA-debug.apk
